spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  thymeleaf:    #禁用缓存
    cache: false
  redis:  #配置redis数据库连接
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: 6000
    database: 0  
  http:
    multipart:
      max-file-size: 200MB #上传一个文件的大小
      max-request-size: 300MB #上传文件的总的大小
    
#配置日志
logging:
  level:
    com.example.demo.mapper: DEBUG
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: debug

  
     
    